version: '3'
services:
  wimo:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
     - "3000:3000"
    depends_on:
     - db
    environment:
     - DB_HOST=db
     - NODE_ENV=development
     - DB_USERNAME=root
     - DB_PASSWORD=iti
     - DB_NAME=wimo_db
     - PORT=3000
    command: sh -c "sleep 1m && 
          ./node_modules/sequelize-cli/lib/sequelize db:migrate &&
          ./node_modules/sequelize-cli/lib/sequelize db:seed:all && 
          npm start"
  db:
    build: ./docker/database
